// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD65-jkhOfjwjJVB1A2aTADhfNuvBWYjKg',
    appId: '1:403189836741:web:54baa29867554f95a2f9ac',
    messagingSenderId: '403189836741',
    projectId: 'certificate-5f9c9',
    authDomain: 'certificate-5f9c9.firebaseapp.com',
    databaseURL: 'https://certificate-5f9c9-default-rtdb.firebaseio.com',
    storageBucket: 'certificate-5f9c9.appspot.com',
    measurementId: 'G-3Q8708H188',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePHZrvaoGm5E5TaVxTwmVGiG8Od48rXE',
    appId: '1:403189836741:android:effc5d17574064a4a2f9ac',
    messagingSenderId: '403189836741',
    projectId: 'certificate-5f9c9',
    databaseURL: 'https://certificate-5f9c9-default-rtdb.firebaseio.com',
    storageBucket: 'certificate-5f9c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClgzCB-PLm7gcgMhbsZi3-gCtFl_nR1-c',
    appId: '1:403189836741:ios:77586e1a599df310a2f9ac',
    messagingSenderId: '403189836741',
    projectId: 'certificate-5f9c9',
    databaseURL: 'https://certificate-5f9c9-default-rtdb.firebaseio.com',
    storageBucket: 'certificate-5f9c9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClgzCB-PLm7gcgMhbsZi3-gCtFl_nR1-c',
    appId: '1:403189836741:ios:77586e1a599df310a2f9ac',
    messagingSenderId: '403189836741',
    projectId: 'certificate-5f9c9',
    databaseURL: 'https://certificate-5f9c9-default-rtdb.firebaseio.com',
    storageBucket: 'certificate-5f9c9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD65-jkhOfjwjJVB1A2aTADhfNuvBWYjKg',
    appId: '1:403189836741:web:f6a062059cb4c3fca2f9ac',
    messagingSenderId: '403189836741',
    projectId: 'certificate-5f9c9',
    authDomain: 'certificate-5f9c9.firebaseapp.com',
    databaseURL: 'https://certificate-5f9c9-default-rtdb.firebaseio.com',
    storageBucket: 'certificate-5f9c9.appspot.com',
    measurementId: 'G-68LXR4DRVE',
  );

}